### ISSUE TITLE
چند سوال

### ISSUE THREAD

**Issue by dreamboxone** [sajjaddg/xray-reality#1]
سلام
بعد از نصب دو تا چیز رو مشخص نمی کنه
اول اینکه پورت چند باید باشه؟
دوم ای پی بدیم به جای آدرس؟
سوم چطوری یوزر جدید بسازیم
ممنونم
اماتورم اما ممنونم از کاری که کردی

**Comment by sajjaddg** [comment]
سلام 
پورتش پیشفرض 443 هست.

**Comment by sajjaddg** [comment]
سلام 
پورتش پیشفرض 443 هست.
بله به جای ادرس ip سرور رو بدید.
فعلا نمیسازه ولی خودتون دستی میتونید اضافه کنید.
